spring:
  application:
    name: SPRINGCLOUD-ZIPKIN
  security:
    user:
      name: admin
      password: You_Password
management:
  metrics:
    web:
      server:
        auto-time-requests: false